# Generated by Django 3.2.7 on 2021-09-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20210922_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
